[2024-07-12T18:51:40.185+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-12T18:51:37.325270+00:00 [queued]>
[2024-07-12T18:51:40.189+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-12T18:51:37.325270+00:00 [queued]>
[2024-07-12T18:51:40.189+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-12T18:51:40.194+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-07-12 18:51:37.325270+00:00
[2024-07-12T18:51:40.197+0000] {standard_task_runner.py:57} INFO - Started process 61 to run task
[2024-07-12T18:51:40.199+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-07-12T18:51:37.325270+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmploqv60wl']
[2024-07-12T18:51:40.200+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask s3_upload
[2024-07-12T18:51:40.218+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-07-12T18:51:37.325270+00:00 [running]> on host a6a45b354d90
[2024-07-12T18:51:40.245+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T18:51:37.325270+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T18:51:37.325270+00:00'
[2024-07-12T18:51:50.568+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-07-12T18:51:50.570+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-07-12T18:51:50.582+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20240712T185137, start_date=20240712T185140, end_date=20240712T185150
[2024-07-12T18:51:50.596+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task s3_upload ('NoneType' object has no attribute 'split'; 61)
[2024-07-12T18:51:50.607+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T18:51:50.621+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
