[2024-07-14T01:11:18.683+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-07-14T01:11:18.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-07-14T01:11:18.688+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-14T01:11:18.693+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extract> on 2024-07-13 00:00:00+00:00
[2024-07-14T01:11:18.699+0000] {standard_task_runner.py:57} INFO - Started process 125 to run task
[2024-07-14T01:11:18.704+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extract', 'scheduled__2024-07-13T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpnh7oey0s']
[2024-07-14T01:11:18.708+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask reddit_extract
[2024-07-14T01:11:18.744+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extract scheduled__2024-07-13T00:00:00+00:00 [running]> on host 4928c5b9e5ae
[2024-07-14T01:11:18.779+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extract' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-13T00:00:00+00:00'
[2024-07-14T01:11:18.787+0000] {logging_mixin.py:151} INFO - Connected to Reddit instance
[2024-07-14T01:11:18.790+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6b0dbb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/dataengineering/top
[2024-07-14T01:11:20.443+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6b0dbf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))")) status: GET https://oauth.reddit.com/r/dataengineering/top
[2024-07-14T01:11:23.583+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 13, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etls.py", line 29, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 51, in _post
    response = self._requestor.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/requestor.py", line 70, in request
    raise RequestException(exc, args, kwargs) from None
prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6b0913d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-07-14T01:11:23.613+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extract, execution_date=20240713T000000, start_date=20240714T011118, end_date=20240714T011123
[2024-07-14T01:11:23.627+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task reddit_extract (error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff6b0913d0>: Failed to establish a new connection: [Errno -2] Name or service not known')); 125)
[2024-07-14T01:11:23.652+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-14T01:11:23.692+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
